### ISSUE TITLE
Evidence Tab Not Rendered Properly With ViewPorts

### ISSUE THREAD

**Issue by AM088204** [cerner/terra-dev-site#353] opened 2021-06-08 10:03 UTC
# Bug Report

## Description
We are using terra-functional-testing^1.0.1 and webpack-config-terra^1.3.1 for running the wdio test cases .wdio snapshots are getting generated properly with all viewports . But In evidence tab , snapshots are not displayed correctly . It should get displayed with all the viewports .
https://github.cerner.com/him-cloud/him-letters-js.git

## Steps to Reproduce

1. Checkout the project https://github.cerner.com/him-cloud/him-letters-js.git and install .
2. Generate wdio snapshots
3. Go to the Evidence tab of the application
4. Check the snapshots present in your machine and Evidence

## Additional Context / Screenshots
![image](https://user-images.githubusercontent.com/80739829/121164297-1ee13c00-c86d-11eb-86b7-ed7bb26c2e3e.png)
![image](https://user-images.githubusercontent.com/80739829/121164918-81d2d300-c86d-11eb-8a5d-918cc27fdb38.png)

## Expected Behavior
Snapshot should render in Evidence tab with all viewports
![image](https://user-images.githubusercontent.com/80739829/121165870-37058b00-c86e-11eb-8dce-8d36d639d039.png)

## Possible Solution
If we delete terra-default-theme folder and put all the snapshot under 'en' folder its rendering correctly .
![image](https://user-images.githubusercontent.com/80739829/121166333-9bc0e580-c86e-11eb-9443-5059f22d4087.png)

## Environment

* Component Name and Version:terra-functional-testing^1.0.1
* Browser Name and Version:Chrome Version 91.0.4472.77 
* Node/npm Version: [e.g. Node 8/npm 5]:npm version 6.13.4
* Webpack Version:webpack-config-terra^1.3.1 
* Operating System and version (desktop or mobile):Desktop Windows

## @ Mentions
@pranav300 @dn043728 @RP078218

**Comment by ryanthemanuel** [comment] 2021-06-08 22:01
In the long run we are planning on deprecating the "evidence" feature of terra-dev-site in lieu of the Test Output section of the orion npm release site (available today) and the Visual Regression section of the release site (will be available in the next few months). I would recommend relying on that functionality as that is the direction that we are moving with our test evidence capturing capabilities.

**Comment by AM088204** [comment] 2021-06-10 05:41
Hi @ryanthemanuel , Thank you for your response . 

Once newer version is released , will it diplay automatically with the generated snapshots with all the viewports
 or do we required any additional code/configuration changes to display those in Visual Regression section ?

**Comment by ryanthemanuel** [comment] 2021-06-11 14:12
@AM088204 yes you will get this functionality in our release site automatically.

**Comment by ryanthemanuel** [comment] 2021-06-18 14:02
Closing this as won't fix since this functionality is being replaced.

**Closed by ryanthemanuel** 2021-06-18 14:02 UTC
Labels: :construction: Blocked: Accessibility Input, :construction: Blocked: Engineering Input, :construction: Blocked: Functional Input, :construction: Blocked: UX Input, :package: terra-dev-site, wontfix
