### ISSUE TITLE
Changes in fragment identifiers causing a re-render of test page components

### ISSUE THREAD

**Issue by zeilmannnoah** [cerner/terra-dev-site#308] opened 2020-10-21 21:17 UTC
# Bug Report

## Description
The terra/orion test page components, [such as this one](https://github.cerner.com/NZ072128/him-coding-summary-js/blob/feature/HIMCLOUD-983_orion_application_uplift/src/orion-dev-site/test/DraftedCodes.test.jsx), are expected to only be rendered once as it often performs set up actions such as creating mock routes. We have noticed that any changes to the URL that should not trigger a refresh or redirect, such as clicking on an anchor tag with the href property set to "#" trigger a re-render of the terra/orion test page component. This is causing an issue for mock routes that are set up to only be allowed to be called once. Typically, it is expected that a fragment identifier(#) does not trigger a refresh of the webpage or any components to re-render unless that logic is built-in.

## Steps to Reproduce
These steps are taken on a sample test page component that just keeps track of the render count and displays an anchor tag that adds a fragment identifier(#) to the url. Link to source code for the sample test page component [here](https://github.cerner.com/NZ072128/him-coding-summary-js/blob/feature/HIMCLOUD-983_orion_application_uplift/src/orion-dev-site/test/TestPageRerender.test.jsx).

1. Open sample test page [here](https://pages.github.cerner.com/NZ072128/him-coding-summary-js/orion-dev-site/raw/tests/him-coding-summary-js/test-page-rerender)
2. Check the console to see that the logged render count is 1.
3. Click on the anchor tag(hyperlink) with the text "Click to test".
4. Check the console to see that the logged render count has incremented to 2.

## Expected Behavior

The expected behavior is that clicking on an anchor tag with the href="#" should not trigger the test page component to re-render. Any change to the url that is prefixed with a hash(#) should not trigger a re-render, even if it is manually entered in the url.

## Possible Solution

I do not have a possible solution as I am not sure what is causing the problem.

## Environment

* Component Name and Version: terra-dev-site
* Browser Name and Version: Seen in chrome, IE, and firefox. 
* Node/npm Version: [e.g. Node 8/npm 5] Seen in node 10.21.0 & npm 6.14.4
* Webpack Version: 4.44.2
* Operating System and version (desktop or mobile): Mac Desktop

## @ Mentions
@mjhenkes and I discussed this issue on [this Team's thread](https://teams.microsoft.com/l/message/19:ec7057f0024d451194d19071dc151f86@thread.skype/1603305938829?tenantId=fbc493a8-0d24-4454-a815-f4ca58e8c09d&groupId=45f47bfa-38a9-444d-8933-9c20266ae38c&parentMessageId=1603305938829&teamName=Terra&channelName=Testing%20Support&createdTime=1603305938829)

**Comment by pranav300** [comment] 2020-12-02 19:58
Had a conversation with @mjhenkes and this is not a bug. Therefore closing this issue.

**Closed by pranav300** 2020-12-02 19:58 UTC
Labels: :construction: Blocked: Engineering Input, :package: terra-dev-site, spike
